# Generated by Django 4.0.6 on 2023-12-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='reference',
            field=models.URLField(blank=True, help_text='Not used in fine-tuning', null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='example',
            name='source_type',
            field=models.ForeignKey(blank=True, help_text='The source of the record', null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.sourcetype'),
        ),
    ]
