# Generated by Django 4.0.6 on 2023-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_sourcetype_example_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='reference',
            new_name='private_reference',
        ),
        migrations.AddField(
            model_name='example',
            name='private_note',
            field=models.TextField(blank=True, help_text='Not used in fine-tuning', null=True),
        ),
    ]
