# Generated by Django 4.0.6 on 2023-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_rename_reference_example_private_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='was_processed',
            field=models.BooleanField(default=False, help_text='Processed in a prior fine-tuning run'),
        ),
    ]
