# Generated by Django 4.0.6 on 2023-12-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_example_was_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTuningJob',
            fields=[
                ('openai_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prior_model', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('fine_tuned_model', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='was_processed',
        ),
        migrations.AddField(
            model_name='example',
            name='fine_tuning_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.finetuningjob'),
        ),
    ]
