# Generated by Django 4.0.6 on 2023-12-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_finetuningjob_remove_example_was_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finetuningjob',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='finetuningjob',
            name='status',
        ),
    ]
