# Generated by Django 4.0.6 on 2023-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_remove_finetuningjob_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetuningjob',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
