# Generated by Django 4.0.6 on 2023-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_finetuningjob_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetuningjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
